style: Seção de Filmes Página Principal
Skaylan/projeto-web-frontend pull request #16
Opened 2024-01-21 19:23 UTC by VerttB

2024-01-25 23:09 UTC, VerttB commented
Grid,  área do título, texto, nota e estrela prontos

Acredito que esteja pronto

2024-01-27 04:24 UTC, Skaylan requested changes

2024-01-27 04:24 UTC, Skaylan commented on src/routes/+page.svelte
> +<head>
As tags html, head, body, ficam no arquivo app.html em qualquer outro arquivo .svelte essas tags não devem ser utilizadas.

2024-01-27 04:24 UTC, Skaylan commented on src/lib/assets/icons8-stars-96.png
O ideal seria se esse icone fosse um .svg ao invés de um .png

2024-01-29 00:36 UTC, VerttB commented
Fiz as mudanças

2024-01-29 11:04 UTC, Skaylan approved these changes
LGTM!

2024-01-29 11:05 UTC, merged