Gui feat
Skaylan/projeto-web-frontend pull request #21
Opened 2024-01-25 19:45 UTC by guilherme3987

Alteração da lógica do carrossel

2024-01-25 23:41 UTC, Skaylan requested changes
Aqui vai ser preciso algumas alterações, o componente carrossel em si deve conter no mesmo arquivo o html o css e o javascript necessários para que ele funcione. Outra coisa que é de extrema importância é que a imagens sejam colocadas em uma tag <img> ao invés de ser colocadas diretamente pelo css, além disse é importante lembrar que tais imagens virão do backend, então para isso utilizando um placeholder https://placehold.co/larguraxaltura.

2024-01-26 18:13 UTC, guilherme3987 commented
Ok vou alterar isso 🤙 Envia o link novamente,pois não abre

On Thu, Jan 25, 2024 at 8:41 PM Lucas G. Oliveira ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Aqui vai ser preciso algumas alterações, o componente carrossel em si deve
> conter no mesmo arquivo o html o css e o javascript necessários para que
> ele funcione. Outra coisa que é de extrema importância é que a imagens
> sejam colocadas em uma tag ao invés de ser colocadas diretamente pelo
> css, além disse é importante lembrar que tais imagens virão do backend,
> então para isso utilizando um placeholder
> https://placehold.co/larguraxaltura.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Skaylan/projeto-web-frontend/pull/21#pullrequestreview-1844880826>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASJDKTXUIFOBFDFSP2KEXTDYQLUTTAVCNFSM6AAAAABCLCLD7SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNBUHA4DAOBSGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-26 20:55 UTC, Skaylan commented
o link é https://placehold.co aí se vc quiser uma imagem com  largura e altura específicos  vc faz https://placehold.co/300x300 por exemplo sendo o primeiro largura e o segundo altura

2024-02-03 14:30 UTC, Skaylan approved these changes
LGTM!

2024-02-03 14:31 UTC, merged