Pagina principal do painel do adm.
Skaylan/projeto-web-frontend pull request #32
Opened 2024-12-28 05:14 UTC by Carlos0101py

2024-12-28 18:14 UTC, Skaylan commented on src/lib/addButton.svelte
> +								{#each uploadTypes as type, i}
rapaz, você testou essa logica para ver se funciona?
esse trecho de código vai diferencias os tipos de upload?

2024-12-28 18:27 UTC, Skaylan commented on src/lib/addButton.svelte
> +					{#each labels as label}
Tem que ver se essa logica vai funcionar. Como você vai pegar os valores de cada um dos inputs? já que eles estão sendo gerados por um loop?

2024-12-28 18:28 UTC, Skaylan commented on src/lib/editButton.svelte
> +                    {#each labels as label}
Tem que ver se essa logica vai funcionar. Como você vai pegar os valores de cada um dos inputs? já que eles estão sendo gerados por um loop?

2024-12-28 18:29 UTC, Skaylan requested changes
Acho que precisa de algumas mudanças antes de fazer o merge com a main. Deixei alguns comentários.

2025-01-12 04:21 UTC, Carlos0101py commented
A pagina esta bem avançada as rotas de recuperação, adição e edição estão funcionando perfeitamente. Falta a implementação da funcionalidade de exclusão, porém ainda estou com problemas no backend.

2025-01-20 02:06 UTC, Skaylan approved these changes
LGTM!

2025-01-20 02:06 UTC, merged